version: '3'

services:
  # elasticsearch:
  #   container_name: elasticsearch-butler
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
  #   env_file:
  #     - ./tools/butler.env
  #   # ports:
  #   #   - 0.0.0.0:9201:9200
  #   #   - 0.0.0.0:9301:9300
  #   environment:
  #     discovery.type: single-node

  # kibana:
  #   container_name: kibana-butler
  #   image: docker.elastic.co/kibana/kibana:7.13.2
  #   env_file:
  #     - ./tools/butler.env
  #   ports:
  #     - 0.0.0.0:5602:5601
  #   environment:
  #     discovery.type: single-node
  #     ELASTICSEARCH_HOSTS: 'http://elasticsearch:9200'
  #   depends_on:
  #     - elasticsearch
  # redis:
  #   container_name: redis-butler
  #   image: redis:6.2.4-alpine
  #   env_file:
  #     - ./tools/butler.env
  #   volumes:
  #     - ./redis-data:/data
  #   command: redis-server --appendonly yes

  postgres:
    container_name: postgres-butler
    image: postgres:13
    env_file:
      - ./tools/butler.env
    volumes:
      - ./postgres-data:/var/lib/postgresql


  butler_web:
    container_name: butler-web
    depends_on:
      - postgres
      # - elasticsearch
      # - kibana
      # - redis

    image: gabrielfalcao/drone-ci-butler
    ports:
      - 0.0.0.0:5000:5000
    volumes:
      - ~/.drone-ci-butler.yml:/drone-ci-butler.yml
    restart: always
    env_file:
      - ./tools/butler.env

    command: drone-ci-butler web

  butler_workers:
    container_name: butler-workers
    image: gabrielfalcao/drone-ci-butler
    depends_on:
      - postgres
      # - elasticsearch
      # - redis
    ports:
      - 0.0.0.0:5001:5001
      - 0.0.0.0:5002:5002
      - 0.0.0.0:5555:5555
      - 0.0.0.0:6666:6666
      - 0.0.0.0:7777:7777

    volumes:
      - ~/.drone-ci-butler.yml:/drone-ci-butler.yml
    restart: always
    env_file:
      - ./tools/butler.env
    environment:
      DRONE_CI_BUTLER_CONFIG_PATH: /drone-ci-butler.yml

    command: drone-ci-butler workers


  butler_builds:
    container_name: butler-builds
    image: gabrielfalcao/drone-ci-butler
    depends_on:
      - postgres
      - butler_workers
      # - elasticsearch
      # - redis

    volumes:
      - ~/.drone-ci-butler.yml:/drone-ci-butler.yml
    restart: always
    environment:
      DRONE_CI_BUTLER_CONFIG_PATH: /drone-ci-butler.yml

    env_file:
      - ./tools/butler.env

    command: sh -c 'sleep 10 && drone-ci-butler builds'
