---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  minReadySeconds: 5
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: elasticsearch
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  template:
    metadata:
      labels:
        app.kubernetes.io/name: elasticsearch

    spec:
      # volumes:
      #   - name: elasticsearch-volume
      #     ephemeral:
      #       volumeClaimTemplate:
      #         metadata:
      #           labels:
      #             type: elasticsearch-volume
      #         spec:
      #           accessModes: [ "ReadWriteOnce" ]
      #           storageClassName: "scratch-storage-class"
      #           resources:
      #             requests:
      #               storage: 100Gi
      containers:
      - image: "elasticsearch:7.13.2"
        imagePullPolicy: IfNotPresent
        name: elasticsearch
        # volumeMounts:
        #   - name: elasticsearch-volume
        #     mountPath: /usr/share/elasticsearch/data
        ports:
        - containerPort: 9200
          name: elasticsearch
        - containerPort: 9300
          name: esbinary
        envFrom:
          - configMapRef:
              name: env
        resources:
          requests:
            ephemeral-storage: "20Gi"
          limits:
            ephemeral-storage: "40Gi"

        env:
          - name: discovery.type
            value: single-node

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app.kubernetes.io/name: elasticsearch

spec:
  type: NodePort
  ports:
    - port: 9200
      targetPort: 9200
      protocol: TCP
      name: elasticsearch

    - port: 9300
      targetPort: 9300
      protocol: TCP
      name: esbinary
  selector:
    app.kubernetes.io/name: elasticsearch
