---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  minReadySeconds: 5
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: kibana
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kibana

    spec:
      # volumes:
      #   - name: kibana-volume
      #     persistentVolumeClaim:
      #       claimName: pvc

      containers:
      - image: "kibana:7.13.2"
        imagePullPolicy: Always
        name: kibana
        # volumeMounts:
        #   - name: kibana-volume
        #     mountPath: /usr/share/kibana/data
        ports:
        - containerPort: 5601
          name: http
        envFrom:
          - configMapRef:
              name: env
        resources:
          requests:
            ephemeral-storage: "10Gi"
          limits:
            ephemeral-storage: "20Gi"

        env:
          - name: discovery.type
            value: single-node
          - name: ELASTICSEARCH_HOSTS
            value: http://drone-ci-butler-elasticsearch.ci-butler.svc.cluster.local:9200

---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app.kubernetes.io/name: kibana

spec:
  type: NodePort
  ports:
    - port: 5601
      targetPort: 5601
      protocol: TCP
      name: http

  selector:
    app.kubernetes.io/name: kibana
