apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: drone-ci-butler

namespace: ci-butler
namePrefix: drone-ci-butler-
# Example configuration for the webserver
# at https://github.com/monopole/hello
commonLabels:
  app-name: drone-ci-butler
  app-runtime: python3.7
  git-revision: fadee85f037537c2d13c9dc7e66ba9f97d364bcb
  app.kubernetes.io/name: drone-ci-butler
  app.kubernetes.io/instance: fadee85f037537c2d13c9dc7e66ba9f97d364bcb


# kustomization.yaml
configMapGenerator:
- name: env
  env: kube.env
- name: ngrok
  env: kube.env
- name: config
  files:
  - drone-ci-butler.yml


resources:
  - postgres.yml
  - elasticsearch.yml
  - kibana.yml
  - redis.yml
  - web.yml
  - workers.yml
  - ngrok.yml
  - dns.yml
