---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngrok
spec:
  minReadySeconds: 5
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: ngrok
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ngrok

    spec:
      containers:
      - image: wernight/ngrok:latest
        imagePullPolicy: Always
        name: ngrok
        # command:
        #   - http
        #   - '--authtoken'
        #   - '{{ .Values.ngrok.token | quote }}'
        #   - '--subdomain'
        #   - '{{ .Values.ngrok.subdomain | quote }}'
        #   - '--bindtls=true'
        #   - '--log=stderr'
        #   - '{{ include "file-server.web.fqdn" . | quote }}'
        envFrom:
          - configMapRef:
              name: ngrok

        env:
          - name: NGROK_SUBDOMAIN
            value: drone-ci-butler

          - name: NGROK_DEBUG
            value: "true"

          - name: NGROK_BINDTLS
            value: "both"

          - name: NGROK_HOSTNAME
            value: "drone-ci-butler.ngrok.io"

          - name: NGROK_PORT
            value: drone-ci-butler-kibana.ci-butler.svc.cluster.local:5604
