---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  minReadySeconds: 5
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres

    spec:
      # volumes:
      #   - name: postgres-volume
      #     ephemeral:
      #       volumeClaimTemplate:
      #         metadata:
      #           labels:
      #             type: postgres-volume
      #         spec:
      #           accessModes: [ "ReadWriteOnce" ]
      #           storageClassName: "scratch-storage-class"
      #           resources:
      #             requests:
      #               storage: 100Gi

      containers:
      - image: "postgres:13"
        imagePullPolicy: IfNotPresent
        name: postgres
        resources:
          requests:
            ephemeral-storage: "1Gi"
          limits:
            ephemeral-storage: "2Gi"

        # volumeMounts:
        #   - name: postgres-volume
        #     mountPath: /var/lib/postgresql


        ports:
        - containerPort: 5432
          name: postgres

        envFrom:
          - configMapRef:
              name: env



---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app.kubernetes.io/name: postgres

spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/name: postgres
