---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-13
spec:
  minReadySeconds: 5
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres-13
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres-13

    spec:
      volumes:
        - name: postgres-volume
          persistentVolumeClaim:
            claimName: pvc

      containers:
      - image: "postgres:13"
        imagePullPolicy: Always
        name: postgres
        volumeMounts:
          - name: postgres-volume
            mountPath: /var/lib/postgresql

        ports:
        - containerPort: 5432
          name: postgres

        envFrom:
          - configMapRef:
              name: env



---
apiVersion: v1
kind: Service
metadata:
  name: postgres-13
  labels:
    app.kubernetes.io/name: postgres-13

spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/name: postgres-13
