---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  minReadySeconds: 5
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis

    spec:
      # volumes:
      #   - name: redis-volume
      #     ephemeral:
      #       volumeClaimTemplate:
      #         metadata:
      #           labels:
      #             type: redis-volume
      #         spec:
      #           accessModes: [ "ReadWriteOnce" ]
      #           storageClassName: "scratch-storage-class"
      #           resources:
      #             requests:
      #               storage: 1Gi
      containers:
      - image: "redis:6.2.4-alpine"
        imagePullPolicy: IfNotPresent
        name: redis
        resources:
          requests:
            ephemeral-storage: "1Gi"
          limits:
            ephemeral-storage: "2Gi"

        # volumeMounts:
        #   - name: redis-volume
        #     mountPath: /data

        ports:
        - containerPort: 6379
          name: redis

        envFrom:
          - configMapRef:
              name: env


---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app.kubernetes.io/name: redis

spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/name: redis
