---
apiVersion: v1
kind: Service
metadata:
  name: drone-ci-butler
  labels:
    app.kubernetes.io/name: web

spec:
  type: NodePort
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: web
