version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:13
    env_file:
      - ./drone.env

  drone:
    container_name: drone
    image: drone/drone:1
    ports:
      - 127.0.0.1:8000:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./drone-data:/data
    restart: always
    env_file:
      - ./drone.env

  runner1:
    container_name: runner
    image: drone/drone-runner-docker:1
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    env_file:
      - ./drone.env
