version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:13
    env_file:
      - ./drone.env
    volumes:
      - ./postgres-data:/var/lib/postgresql

  drone:
    container_name: drone
    image: drone/drone:1
    ports:
      - 127.0.0.1:8000:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./drone-data:/data
    restart: always
    env_file:
      - ./drone.env

  runner1:
    container_name: runner1
    image: drone/drone-runner-docker:1
    environment:
      DRONE_HTTP_BIND: 3033
    ports:
      - 127.0.0.1:3033:3033
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    env_file:
      - ./drone.env


  runner2:
    container_name: runner2
    image: drone/drone-runner-docker:1
    environment:
      DRONE_HTTP_BIND: 3031
    ports:
      - 127.0.0.1:3031:3031
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    env_file:
      - ./drone.env
