name: ⚙️ Base Docker Image
defaults:
  run:
    working-directory: ./

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: K8S Docker Image (Kubernetes Deployment)
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: gabrielfalcao/drone-ci-butler-base
        dockerfile: Dockerfile.base
        path: .
        tag_with_ref: true
        tag_with_sha: true
        tags: "${{ github.sha }}"
